// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var MaterialUi_Grid = require("@jsiebern/bs-material-ui/src/MaterialUi_Grid.bs.js");
var MaterialUi_Paper = require("@jsiebern/bs-material-ui/src/MaterialUi_Paper.bs.js");
var Core = require("@material-ui/core");

function str(prim) {
  return prim;
}

function str_int(number) {
  return String(number);
}

function reducer(state, action) {
  console.log(state);
  if (typeof action === "number") {
    switch (action) {
      case 0 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0] + 1 | 0,
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 1 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1] + 1 | 0,
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 2 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions : :: */[
                    /* UNDO */2,
                    state[/* actions */11]
                  ],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      
    }
  } else {
    switch (action.tag | 0) {
      case 0 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */action[0],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 1 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */action[0],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 2 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */action[0],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 3 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */action[0],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 5 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */action[0],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 6 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */action[0],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 7 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */action[0],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 4 : 
      case 8 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */action[0],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */state[/* screen */12],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 9 : 
          return /* record */[
                  /* scoreH */state[/* scoreH */0],
                  /* scoreA */state[/* scoreA */1],
                  /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                  /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                  /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                  /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                  /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                  /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                  /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                  /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                  /* notes */state[/* notes */10],
                  /* actions */state[/* actions */11],
                  /* screen */action[0],
                  /* serviceOrderSet1 */state[/* serviceOrderSet1 */13],
                  /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                  /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                ];
      case 10 : 
          switch (action[0]) {
            case 0 : 
            case 1 : 
                return /* record */[
                        /* scoreH */state[/* scoreH */0],
                        /* scoreA */state[/* scoreA */1],
                        /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                        /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                        /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                        /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                        /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                        /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                        /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                        /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                        /* notes */state[/* notes */10],
                        /* actions */state[/* actions */11],
                        /* screen */state[/* screen */12],
                        /* serviceOrderSet1 : :: */[
                          /* Player2Hometeam */1,
                          state[/* serviceOrderSet1 */13]
                        ],
                        /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                        /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                      ];
            case 2 : 
                return /* record */[
                        /* scoreH */state[/* scoreH */0],
                        /* scoreA */state[/* scoreA */1],
                        /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                        /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                        /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                        /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                        /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                        /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                        /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                        /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                        /* notes */state[/* notes */10],
                        /* actions */state[/* actions */11],
                        /* screen */state[/* screen */12],
                        /* serviceOrderSet1 : :: */[
                          /* Player1Awayteam */2,
                          state[/* serviceOrderSet1 */13]
                        ],
                        /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                        /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                      ];
            case 3 : 
                return /* record */[
                        /* scoreH */state[/* scoreH */0],
                        /* scoreA */state[/* scoreA */1],
                        /* namePlayer1Hometeam */state[/* namePlayer1Hometeam */2],
                        /* namePlayer2Hometeam */state[/* namePlayer2Hometeam */3],
                        /* namePlayer1Awayteam */state[/* namePlayer1Awayteam */4],
                        /* namePlayer2Awayteam */state[/* namePlayer2Awayteam */5],
                        /* jerseyColorPlayer1Hometeam */state[/* jerseyColorPlayer1Hometeam */6],
                        /* jerseyColorPlayer2Hometeam */state[/* jerseyColorPlayer2Hometeam */7],
                        /* jerseyColorPlayer1Awayteam */state[/* jerseyColorPlayer1Awayteam */8],
                        /* jerseyColorPlayer2Awayteam */state[/* jerseyColorPlayer2Awayteam */9],
                        /* notes */state[/* notes */10],
                        /* actions */state[/* actions */11],
                        /* screen */state[/* screen */12],
                        /* serviceOrderSet1 : :: */[
                          /* Player2Awayteam */3,
                          state[/* serviceOrderSet1 */13]
                        ],
                        /* serviceOrderSet2 */state[/* serviceOrderSet2 */14],
                        /* serviceOrderSet3 */state[/* serviceOrderSet3 */15]
                      ];
            
          }
      
    }
  }
}

function App(Props) {
  return React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(null), undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, /* V3 */3, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(React.createElement(Core.Paper, MaterialUi_Paper.makeProps("xs=6", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V6 */5, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)), React.createElement(Core.Grid, MaterialUi_Grid.makeProps(undefined, undefined, Caml_option.some(React.createElement(Core.Paper, MaterialUi_Paper.makeProps("xs=6", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0))), undefined, undefined, undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* V6 */5, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, /* () */0)));
}

var MenuIcon = 0;

var initialState = /* record */[
  /* scoreH */1,
  /* scoreA */0,
  /* namePlayer1Hometeam */"",
  /* namePlayer2Hometeam */"",
  /* namePlayer1Awayteam */"",
  /* namePlayer2Awayteam */"",
  /* jerseyColorPlayer1Hometeam */"",
  /* jerseyColorPlayer2Hometeam */"",
  /* jerseyColorPlayer1Awayteam */"",
  /* jerseyColorPlayer2Awayteam */"",
  /* notes : [] */0,
  /* actions : [] */0,
  /* screen : GameScreen */0,
  /* serviceOrderSet1 : [] */0,
  /* serviceOrderSet2 : [] */0,
  /* serviceOrderSet3 : [] */0
];

var make = App;

exports.MenuIcon = MenuIcon;
exports.str = str;
exports.str_int = str_int;
exports.initialState = initialState;
exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
