// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function str_int(number) {
  return String(number);
}

var initialState = /* record */[
  /* scoreH */0,
  /* scoreA */0
];

function Component2(Props) {
  var match = React.useReducer((function (state, action) {
          if (action) {
            return /* record */[
                    /* scoreH */state[/* scoreH */0],
                    /* scoreA */state[/* scoreA */1] + 1 | 0
                  ];
          } else {
            return /* record */[
                    /* scoreH */state[/* scoreH */0] + 1 | 0,
                    /* scoreA */state[/* scoreA */1]
                  ];
          }
        }), initialState);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement("div", undefined, React.createElement("div", undefined, String(state[/* scoreH */0])), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* AddPointsHometeam */0);
                    })
                }, "Add Point"), React.createElement("div", undefined, String(state[/* scoreA */1])), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* AddPointsAwayteam */1);
                    })
                }, "Add Point"));
}

var make = Component2;

exports.str = str;
exports.str_int = str_int;
exports.initialState = initialState;
exports.make = make;
/* react Not a pure module */
