// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App2$ReactHooksTemplate = require("./App2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App2$ReactHooksTemplate.make, { }), "index2");

/*  Not a pure module */
