// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function str(prim) {
  return prim;
}

function TeamSettingsAwayTeam(Props) {
  var state = Props.state;
  return React.createElement("p", undefined, "Hei " + String(state[/* scoreA */1]));
}

var make = TeamSettingsAwayTeam;

exports.str = str;
exports.make = make;
/* react Not a pure module */
